package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	pb "github.com/elebirds/panoptes/internal/gen/proto"
	"google.golang.org/protobuf/reflect/protoreflect"
)

type commandSpec struct {
	interfaceName string
	dispatchName  string
	message       protoreflect.MessageDescriptor
	nilBody       string
	nilHandler    string
	unsupported   string
}

func main() {
	specs := []commandSpec{
		{
			interfaceName: "AuthHandler",
			dispatchName:  "DispatchAuthCommand",
			message:       (&pb.AuthCommand{}).ProtoReflect().Descriptor(),
			nilBody:       "auth command body is required",
			nilHandler:    "auth handler is not configured",
			unsupported:   "unsupported auth command",
		},
		{
			interfaceName: "LobbyHandler",
			dispatchName:  "DispatchLobbyCommand",
			message:       (&pb.LobbyCommand{}).ProtoReflect().Descriptor(),
			nilBody:       "lobby command body is required",
			nilHandler:    "lobby handler is not configured",
			unsupported:   "unsupported lobby command",
		},
		{
			interfaceName: "PlanningHandler",
			dispatchName:  "DispatchPlanningCommand",
			message:       (&pb.PlanningCommand{}).ProtoReflect().Descriptor(),
			nilBody:       "planning command body is required",
			nilHandler:    "planning handler is not configured",
			unsupported:   "unsupported planning command",
		},
		{
			interfaceName: "GameHandler",
			dispatchName:  "DispatchGameCommand",
			message:       (&pb.GameCommand{}).ProtoReflect().Descriptor(),
			nilBody:       "game command body is required",
			nilHandler:    "game handler is not configured",
			unsupported:   "unsupported game command",
		},
	}

	var out bytes.Buffer
	writeLine(&out, "// Code generated by transportdispatchgen. DO NOT EDIT.")
	writeLine(&out, "")
	writeLine(&out, "package dispatch")
	writeLine(&out, "")
	writeLine(&out, "import (")
	writeLine(&out, "\tpb \"github.com/elebirds/panoptes/internal/gen/proto\"")
	writeLine(&out, "\ttransportproblem \"github.com/elebirds/panoptes/internal/transport/problem\"")
	writeLine(&out, ")")

	for _, spec := range specs {
		emitInterface(&out, spec)
		emitDispatch(&out, spec)
	}

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		panic(err)
	}

	outputPath := filepath.Join("internal", "transport", "dispatch", "generated_commands.go")
	if err := os.WriteFile(outputPath, formatted, 0o644); err != nil {
		panic(err)
	}
}

func emitInterface(out *bytes.Buffer, spec commandSpec) {
	writeLine(out, "")
	writeLine(out, fmt.Sprintf("type %s interface {", spec.interfaceName))
	for _, branch := range branches(spec.message) {
		writeLine(out, fmt.Sprintf("\t%s(ctx InboundContext, cmd *pb.%s) error", branch.methodName, branch.messageName))
	}
	writeLine(out, "}")
}

func emitDispatch(out *bytes.Buffer, spec commandSpec) {
	commandName := spec.message.Name()
	writeLine(out, "")
	writeLine(out, fmt.Sprintf("func %s(ctx InboundContext, cmd *pb.%s, handler %s) error {", spec.dispatchName, commandName, spec.interfaceName))
	writeLine(out, "\tif cmd == nil || cmd.Body == nil {")
	writeLine(out, fmt.Sprintf("\t\treturn transportproblem.InvalidRequest(%q)", spec.nilBody))
	writeLine(out, "\t}")
	writeLine(out, "\tif handler == nil {")
	writeLine(out, fmt.Sprintf("\t\treturn transportproblem.InternalError(%q)", spec.nilHandler))
	writeLine(out, "\t}")
	writeLine(out, "")
	writeLine(out, "\tswitch body := cmd.Body.(type) {")
	for _, branch := range branches(spec.message) {
		writeLine(out, fmt.Sprintf("\tcase *pb.%s_%s:", commandName, branch.methodName))
		writeLine(out, fmt.Sprintf("\t\treturn handler.%s(ctx, body.%s)", branch.methodName, branch.methodName))
	}
	writeLine(out, "\tdefault:")
	writeLine(out, fmt.Sprintf("\t\treturn transportproblem.UnsupportedCommand(%q)", spec.unsupported))
	writeLine(out, "\t}")
	writeLine(out, "}")
}

type branchSpec struct {
	methodName  string
	messageName string
}

func branches(message protoreflect.MessageDescriptor) []branchSpec {
	oneofs := message.Oneofs()
	if oneofs.Len() == 0 {
		return nil
	}

	oneof := oneofs.Get(0)
	fields := oneof.Fields()
	result := make([]branchSpec, 0, fields.Len())
	for i := 0; i < fields.Len(); i++ {
		field := fields.Get(i)
		result = append(result, branchSpec{
			methodName:  goExported(field.Name()),
			messageName: string(field.Message().Name()),
		})
	}
	return result
}

func goExported(name protoreflect.Name) string {
	parts := strings.Split(string(name), "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func writeLine(out *bytes.Buffer, line string) {
	out.WriteString(line)
	out.WriteByte('\n')
}
