// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: panoptes/proto/v1/settlement.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Panoptes.Protocol.V1 {

  /// <summary>Holder for reflection information generated from panoptes/proto/v1/settlement.proto</summary>
  public static partial class SettlementReflection {

    #region Descriptor
    /// <summary>File descriptor for panoptes/proto/v1/settlement.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SettlementReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiJwYW5vcHRlcy9wcm90by92MS9zZXR0bGVtZW50LnByb3RvEhFwYW5vcHRl",
            "cy5wcm90by52MRoicGFub3B0ZXMvcHJvdG8vdjEvZ2FtZV9zdGF0ZS5wcm90",
            "byKUAQoJVHVybkV2ZW50EhIKBHR5cGUYASABKAlSBHR5cGUSOgoEZGF0YRgC",
            "IAMoCzImLnBhbm9wdGVzLnByb3RvLnYxLlR1cm5FdmVudC5EYXRhRW50cnlS",
            "BGRhdGEaNwoJRGF0YUVudHJ5EhAKA2tleRgBIAEoCVIDa2V5EhQKBXZhbHVl",
            "GAIgASgJUgV2YWx1ZToCOAEiYwoRU2V0dGxlbWVudFNlY3Rpb24SGAoHc2Vj",
            "dGlvbhgBIAEoCVIHc2VjdGlvbhI0CgZldmVudHMYAiADKAsyHC5wYW5vcHRl",
            "cy5wcm90by52MS5UdXJuRXZlbnRSBmV2ZW50cyLLAgoRTXNnVHVyblNldHRs",
            "ZW1lbnQSQAoIc2VjdGlvbnMYASADKAsyJC5wYW5vcHRlcy5wcm90by52MS5T",
            "ZXR0bGVtZW50U2VjdGlvblIIc2VjdGlvbnMSEgoEdHVybhgCIAEoBVIEdHVy",
            "bhIUCgVwaGFzZRgDIAEoCVIFcGhhc2USHQoKbmV4dF9waGFzZRgEIAEoCVIJ",
            "bmV4dFBoYXNlEjEKBW5vZGVzGAUgAygLMhsucGFub3B0ZXMucHJvdG8udjEu",
            "Tm9kZVZpZXdSBW5vZGVzEjEKBXVuaXRzGAYgAygLMhsucGFub3B0ZXMucHJv",
            "dG8udjEuVW5pdFZpZXdSBXVuaXRzEkUKD215X3BsYXllcl9hZnRlchgHIAEo",
            "CzIdLnBhbm9wdGVzLnByb3RvLnYxLlBsYXllclZpZXdSDW15UGxheWVyQWZ0",
            "ZXJCUFo3Z2l0aHViLmNvbS9lbGViaXJkcy9wYW5vcHRlcy9pbnRlcm5hbC9n",
            "ZW4vcHJvdG87cHJvdG92MaoCFFBhbm9wdGVzLlByb3RvY29sLlYxYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Panoptes.Protocol.V1.GameStateReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Panoptes.Protocol.V1.TurnEvent), global::Panoptes.Protocol.V1.TurnEvent.Parser, new[]{ "Type", "Data" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::Panoptes.Protocol.V1.SettlementSection), global::Panoptes.Protocol.V1.SettlementSection.Parser, new[]{ "Section", "Events" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Panoptes.Protocol.V1.MsgTurnSettlement), global::Panoptes.Protocol.V1.MsgTurnSettlement.Parser, new[]{ "Sections", "Turn", "Phase", "NextPhase", "Nodes", "Units", "MyPlayerAfter" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TurnEvent : pb::IMessage<TurnEvent>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TurnEvent> _parser = new pb::MessageParser<TurnEvent>(() => new TurnEvent());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TurnEvent> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Panoptes.Protocol.V1.SettlementReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TurnEvent() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TurnEvent(TurnEvent other) : this() {
      type_ = other.type_;
      data_ = other.data_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TurnEvent Clone() {
      return new TurnEvent(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 2;
    private static readonly pbc::MapField<string, string>.Codec _map_data_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 18);
    private readonly pbc::MapField<string, string> data_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Data {
      get { return data_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TurnEvent);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TurnEvent other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (!Data.Equals(other.Data)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      data_.WriteTo(output, _map_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Type);
      }
      data_.WriteTo(ref output, _map_data_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      size += data_.CalculateSize(_map_data_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TurnEvent other) {
      if (other == null) {
        return;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      data_.MergeFrom(other.data_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            data_.AddEntriesFrom(input, _map_data_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Type = input.ReadString();
            break;
          }
          case 18: {
            data_.AddEntriesFrom(ref input, _map_data_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class SettlementSection : pb::IMessage<SettlementSection>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SettlementSection> _parser = new pb::MessageParser<SettlementSection>(() => new SettlementSection());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SettlementSection> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Panoptes.Protocol.V1.SettlementReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettlementSection() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettlementSection(SettlementSection other) : this() {
      section_ = other.section_;
      events_ = other.events_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SettlementSection Clone() {
      return new SettlementSection(this);
    }

    /// <summary>Field number for the "section" field.</summary>
    public const int SectionFieldNumber = 1;
    private string section_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Section {
      get { return section_; }
      set {
        section_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "events" field.</summary>
    public const int EventsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Panoptes.Protocol.V1.TurnEvent> _repeated_events_codec
        = pb::FieldCodec.ForMessage(18, global::Panoptes.Protocol.V1.TurnEvent.Parser);
    private readonly pbc::RepeatedField<global::Panoptes.Protocol.V1.TurnEvent> events_ = new pbc::RepeatedField<global::Panoptes.Protocol.V1.TurnEvent>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Panoptes.Protocol.V1.TurnEvent> Events {
      get { return events_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SettlementSection);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SettlementSection other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Section != other.Section) return false;
      if(!events_.Equals(other.events_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Section.Length != 0) hash ^= Section.GetHashCode();
      hash ^= events_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Section.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Section);
      }
      events_.WriteTo(output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Section.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Section);
      }
      events_.WriteTo(ref output, _repeated_events_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Section.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Section);
      }
      size += events_.CalculateSize(_repeated_events_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SettlementSection other) {
      if (other == null) {
        return;
      }
      if (other.Section.Length != 0) {
        Section = other.Section;
      }
      events_.Add(other.events_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Section = input.ReadString();
            break;
          }
          case 18: {
            events_.AddEntriesFrom(input, _repeated_events_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Section = input.ReadString();
            break;
          }
          case 18: {
            events_.AddEntriesFrom(ref input, _repeated_events_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class MsgTurnSettlement : pb::IMessage<MsgTurnSettlement>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MsgTurnSettlement> _parser = new pb::MessageParser<MsgTurnSettlement>(() => new MsgTurnSettlement());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MsgTurnSettlement> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Panoptes.Protocol.V1.SettlementReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTurnSettlement() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTurnSettlement(MsgTurnSettlement other) : this() {
      sections_ = other.sections_.Clone();
      turn_ = other.turn_;
      phase_ = other.phase_;
      nextPhase_ = other.nextPhase_;
      nodes_ = other.nodes_.Clone();
      units_ = other.units_.Clone();
      myPlayerAfter_ = other.myPlayerAfter_ != null ? other.myPlayerAfter_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MsgTurnSettlement Clone() {
      return new MsgTurnSettlement(this);
    }

    /// <summary>Field number for the "sections" field.</summary>
    public const int SectionsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Panoptes.Protocol.V1.SettlementSection> _repeated_sections_codec
        = pb::FieldCodec.ForMessage(10, global::Panoptes.Protocol.V1.SettlementSection.Parser);
    private readonly pbc::RepeatedField<global::Panoptes.Protocol.V1.SettlementSection> sections_ = new pbc::RepeatedField<global::Panoptes.Protocol.V1.SettlementSection>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Panoptes.Protocol.V1.SettlementSection> Sections {
      get { return sections_; }
    }

    /// <summary>Field number for the "turn" field.</summary>
    public const int TurnFieldNumber = 2;
    private int turn_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Turn {
      get { return turn_; }
      set {
        turn_ = value;
      }
    }

    /// <summary>Field number for the "phase" field.</summary>
    public const int PhaseFieldNumber = 3;
    private string phase_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Phase {
      get { return phase_; }
      set {
        phase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "next_phase" field.</summary>
    public const int NextPhaseFieldNumber = 4;
    private string nextPhase_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string NextPhase {
      get { return nextPhase_; }
      set {
        nextPhase_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nodes" field.</summary>
    public const int NodesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::Panoptes.Protocol.V1.NodeView> _repeated_nodes_codec
        = pb::FieldCodec.ForMessage(42, global::Panoptes.Protocol.V1.NodeView.Parser);
    private readonly pbc::RepeatedField<global::Panoptes.Protocol.V1.NodeView> nodes_ = new pbc::RepeatedField<global::Panoptes.Protocol.V1.NodeView>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Panoptes.Protocol.V1.NodeView> Nodes {
      get { return nodes_; }
    }

    /// <summary>Field number for the "units" field.</summary>
    public const int UnitsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Panoptes.Protocol.V1.UnitView> _repeated_units_codec
        = pb::FieldCodec.ForMessage(50, global::Panoptes.Protocol.V1.UnitView.Parser);
    private readonly pbc::RepeatedField<global::Panoptes.Protocol.V1.UnitView> units_ = new pbc::RepeatedField<global::Panoptes.Protocol.V1.UnitView>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Panoptes.Protocol.V1.UnitView> Units {
      get { return units_; }
    }

    /// <summary>Field number for the "my_player_after" field.</summary>
    public const int MyPlayerAfterFieldNumber = 7;
    private global::Panoptes.Protocol.V1.PlayerView myPlayerAfter_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Panoptes.Protocol.V1.PlayerView MyPlayerAfter {
      get { return myPlayerAfter_; }
      set {
        myPlayerAfter_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MsgTurnSettlement);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MsgTurnSettlement other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!sections_.Equals(other.sections_)) return false;
      if (Turn != other.Turn) return false;
      if (Phase != other.Phase) return false;
      if (NextPhase != other.NextPhase) return false;
      if(!nodes_.Equals(other.nodes_)) return false;
      if(!units_.Equals(other.units_)) return false;
      if (!object.Equals(MyPlayerAfter, other.MyPlayerAfter)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= sections_.GetHashCode();
      if (Turn != 0) hash ^= Turn.GetHashCode();
      if (Phase.Length != 0) hash ^= Phase.GetHashCode();
      if (NextPhase.Length != 0) hash ^= NextPhase.GetHashCode();
      hash ^= nodes_.GetHashCode();
      hash ^= units_.GetHashCode();
      if (myPlayerAfter_ != null) hash ^= MyPlayerAfter.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      sections_.WriteTo(output, _repeated_sections_codec);
      if (Turn != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Turn);
      }
      if (Phase.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Phase);
      }
      if (NextPhase.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NextPhase);
      }
      nodes_.WriteTo(output, _repeated_nodes_codec);
      units_.WriteTo(output, _repeated_units_codec);
      if (myPlayerAfter_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MyPlayerAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      sections_.WriteTo(ref output, _repeated_sections_codec);
      if (Turn != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Turn);
      }
      if (Phase.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(Phase);
      }
      if (NextPhase.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(NextPhase);
      }
      nodes_.WriteTo(ref output, _repeated_nodes_codec);
      units_.WriteTo(ref output, _repeated_units_codec);
      if (myPlayerAfter_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(MyPlayerAfter);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += sections_.CalculateSize(_repeated_sections_codec);
      if (Turn != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Turn);
      }
      if (Phase.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Phase);
      }
      if (NextPhase.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(NextPhase);
      }
      size += nodes_.CalculateSize(_repeated_nodes_codec);
      size += units_.CalculateSize(_repeated_units_codec);
      if (myPlayerAfter_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MyPlayerAfter);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MsgTurnSettlement other) {
      if (other == null) {
        return;
      }
      sections_.Add(other.sections_);
      if (other.Turn != 0) {
        Turn = other.Turn;
      }
      if (other.Phase.Length != 0) {
        Phase = other.Phase;
      }
      if (other.NextPhase.Length != 0) {
        NextPhase = other.NextPhase;
      }
      nodes_.Add(other.nodes_);
      units_.Add(other.units_);
      if (other.myPlayerAfter_ != null) {
        if (myPlayerAfter_ == null) {
          MyPlayerAfter = new global::Panoptes.Protocol.V1.PlayerView();
        }
        MyPlayerAfter.MergeFrom(other.MyPlayerAfter);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            sections_.AddEntriesFrom(input, _repeated_sections_codec);
            break;
          }
          case 16: {
            Turn = input.ReadInt32();
            break;
          }
          case 26: {
            Phase = input.ReadString();
            break;
          }
          case 34: {
            NextPhase = input.ReadString();
            break;
          }
          case 42: {
            nodes_.AddEntriesFrom(input, _repeated_nodes_codec);
            break;
          }
          case 50: {
            units_.AddEntriesFrom(input, _repeated_units_codec);
            break;
          }
          case 58: {
            if (myPlayerAfter_ == null) {
              MyPlayerAfter = new global::Panoptes.Protocol.V1.PlayerView();
            }
            input.ReadMessage(MyPlayerAfter);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            sections_.AddEntriesFrom(ref input, _repeated_sections_codec);
            break;
          }
          case 16: {
            Turn = input.ReadInt32();
            break;
          }
          case 26: {
            Phase = input.ReadString();
            break;
          }
          case 34: {
            NextPhase = input.ReadString();
            break;
          }
          case 42: {
            nodes_.AddEntriesFrom(ref input, _repeated_nodes_codec);
            break;
          }
          case 50: {
            units_.AddEntriesFrom(ref input, _repeated_units_codec);
            break;
          }
          case 58: {
            if (myPlayerAfter_ == null) {
              MyPlayerAfter = new global::Panoptes.Protocol.V1.PlayerView();
            }
            input.ReadMessage(MyPlayerAfter);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
