// Code generated by transportdispatchgen. DO NOT EDIT.

package dispatch

import (
	pb "github.com/elebirds/panoptes/internal/gen/proto"
	transportproblem "github.com/elebirds/panoptes/internal/transport/problem"
)

type AuthHandler interface {
	Register(ctx InboundContext, cmd *pb.MsgRegister) error
	Login(ctx InboundContext, cmd *pb.MsgLogin) error
}

func DispatchAuthCommand(ctx InboundContext, cmd *pb.AuthCommand, handler AuthHandler) error {
	if cmd == nil || cmd.Body == nil {
		return transportproblem.InvalidRequest("auth command body is required")
	}
	if handler == nil {
		return transportproblem.InternalError("auth handler is not configured")
	}

	switch body := cmd.Body.(type) {
	case *pb.AuthCommand_Register:
		return handler.Register(ctx, body.Register)
	case *pb.AuthCommand_Login:
		return handler.Login(ctx, body.Login)
	default:
		return transportproblem.UnsupportedCommand("unsupported auth command")
	}
}

type LobbyHandler interface {
	CreateRoom(ctx InboundContext, cmd *pb.MsgCreateRoom) error
	JoinRoom(ctx InboundContext, cmd *pb.MsgJoinRoom) error
	LeaveRoom(ctx InboundContext, cmd *pb.MsgLeaveRoom) error
	ReadyUp(ctx InboundContext, cmd *pb.MsgReadyUp) error
	AddBot(ctx InboundContext, cmd *pb.MsgAddBot) error
	StartGame(ctx InboundContext, cmd *pb.MsgStartGame) error
	KickPlayer(ctx InboundContext, cmd *pb.MsgKickPlayer) error
}

func DispatchLobbyCommand(ctx InboundContext, cmd *pb.LobbyCommand, handler LobbyHandler) error {
	if cmd == nil || cmd.Body == nil {
		return transportproblem.InvalidRequest("lobby command body is required")
	}
	if handler == nil {
		return transportproblem.InternalError("lobby handler is not configured")
	}

	switch body := cmd.Body.(type) {
	case *pb.LobbyCommand_CreateRoom:
		return handler.CreateRoom(ctx, body.CreateRoom)
	case *pb.LobbyCommand_JoinRoom:
		return handler.JoinRoom(ctx, body.JoinRoom)
	case *pb.LobbyCommand_LeaveRoom:
		return handler.LeaveRoom(ctx, body.LeaveRoom)
	case *pb.LobbyCommand_ReadyUp:
		return handler.ReadyUp(ctx, body.ReadyUp)
	case *pb.LobbyCommand_AddBot:
		return handler.AddBot(ctx, body.AddBot)
	case *pb.LobbyCommand_StartGame:
		return handler.StartGame(ctx, body.StartGame)
	case *pb.LobbyCommand_KickPlayer:
		return handler.KickPlayer(ctx, body.KickPlayer)
	default:
		return transportproblem.UnsupportedCommand("unsupported lobby command")
	}
}

type ChatHandler interface {
	SendGameChat(ctx InboundContext, cmd *pb.MsgSendGameChat) error
}

func DispatchChatCommand(ctx InboundContext, cmd *pb.ChatCommand, handler ChatHandler) error {
	if cmd == nil || cmd.Body == nil {
		return transportproblem.InvalidRequest("chat command body is required")
	}
	if handler == nil {
		return transportproblem.InternalError("chat handler is not configured")
	}

	switch body := cmd.Body.(type) {
	case *pb.ChatCommand_SendGameChat:
		return handler.SendGameChat(ctx, body.SendGameChat)
	default:
		return transportproblem.UnsupportedCommand("unsupported chat command")
	}
}

type PlanningHandler interface {
	SetPolicy(ctx InboundContext, cmd *pb.MsgSetPolicy) error
	SetResearchTarget(ctx InboundContext, cmd *pb.MsgSetResearchTarget) error
	SetBuildingRecipe(ctx InboundContext, cmd *pb.MsgSetBuildingRecipe) error
	BuildStructure(ctx InboundContext, cmd *pb.MsgBuildStructure) error
	RevealNode(ctx InboundContext, cmd *pb.MsgRevealNode) error
	SetWarZone(ctx InboundContext, cmd *pb.MsgSetWarZone) error
	WarZoneDirective(ctx InboundContext, cmd *pb.MsgWarZoneDirective) error
	SetMinisterDirective(ctx InboundContext, cmd *pb.MsgSetMinisterDirective) error
	IssueUnitOrder(ctx InboundContext, cmd *pb.MsgIssueUnitOrder) error
	CancelUnitOrder(ctx InboundContext, cmd *pb.MsgCancelUnitOrder) error
	PlanningPathPreviewRequest(ctx InboundContext, cmd *pb.MsgPlanningPathPreviewRequest) error
	SubmitTurn(ctx InboundContext, cmd *pb.MsgSubmitTurn) error
	SetInstitutionLoadout(ctx InboundContext, cmd *pb.MsgSetInstitutionLoadout) error
	BuildStructurePreview(ctx InboundContext, cmd *pb.MsgBuildStructurePreviewRequest) error
	SetBuildingRecipePreview(ctx InboundContext, cmd *pb.MsgSetBuildingRecipePreviewRequest) error
}

func DispatchPlanningCommand(ctx InboundContext, cmd *pb.PlanningCommand, handler PlanningHandler) error {
	if cmd == nil || cmd.Body == nil {
		return transportproblem.InvalidRequest("planning command body is required")
	}
	if handler == nil {
		return transportproblem.InternalError("planning handler is not configured")
	}

	switch body := cmd.Body.(type) {
	case *pb.PlanningCommand_SetPolicy:
		return handler.SetPolicy(ctx, body.SetPolicy)
	case *pb.PlanningCommand_SetResearchTarget:
		return handler.SetResearchTarget(ctx, body.SetResearchTarget)
	case *pb.PlanningCommand_SetBuildingRecipe:
		return handler.SetBuildingRecipe(ctx, body.SetBuildingRecipe)
	case *pb.PlanningCommand_BuildStructure:
		return handler.BuildStructure(ctx, body.BuildStructure)
	case *pb.PlanningCommand_RevealNode:
		return handler.RevealNode(ctx, body.RevealNode)
	case *pb.PlanningCommand_SetWarZone:
		return handler.SetWarZone(ctx, body.SetWarZone)
	case *pb.PlanningCommand_WarZoneDirective:
		return handler.WarZoneDirective(ctx, body.WarZoneDirective)
	case *pb.PlanningCommand_SetMinisterDirective:
		return handler.SetMinisterDirective(ctx, body.SetMinisterDirective)
	case *pb.PlanningCommand_IssueUnitOrder:
		return handler.IssueUnitOrder(ctx, body.IssueUnitOrder)
	case *pb.PlanningCommand_CancelUnitOrder:
		return handler.CancelUnitOrder(ctx, body.CancelUnitOrder)
	case *pb.PlanningCommand_PlanningPathPreviewRequest:
		return handler.PlanningPathPreviewRequest(ctx, body.PlanningPathPreviewRequest)
	case *pb.PlanningCommand_SubmitTurn:
		return handler.SubmitTurn(ctx, body.SubmitTurn)
	case *pb.PlanningCommand_SetInstitutionLoadout:
		return handler.SetInstitutionLoadout(ctx, body.SetInstitutionLoadout)
	case *pb.PlanningCommand_BuildStructurePreview:
		return handler.BuildStructurePreview(ctx, body.BuildStructurePreview)
	case *pb.PlanningCommand_SetBuildingRecipePreview:
		return handler.SetBuildingRecipePreview(ctx, body.SetBuildingRecipePreview)
	default:
		return transportproblem.UnsupportedCommand("unsupported planning command")
	}
}

type GameHandler interface {
	Planning(ctx InboundContext, cmd *pb.PlanningCommand) error
	StaticCatalogSyncRequest(ctx InboundContext, cmd *pb.MsgStaticCatalogSyncRequest) error
	Chat(ctx InboundContext, cmd *pb.ChatCommand) error
	CommandBatch(ctx InboundContext, cmd *pb.MsgGameCommandBatch) error
}

func DispatchGameCommand(ctx InboundContext, cmd *pb.GameCommand, handler GameHandler) error {
	if cmd == nil || cmd.Body == nil {
		return transportproblem.InvalidRequest("game command body is required")
	}
	if handler == nil {
		return transportproblem.InternalError("game handler is not configured")
	}

	switch body := cmd.Body.(type) {
	case *pb.GameCommand_Planning:
		return handler.Planning(ctx, body.Planning)
	case *pb.GameCommand_StaticCatalogSyncRequest:
		return handler.StaticCatalogSyncRequest(ctx, body.StaticCatalogSyncRequest)
	case *pb.GameCommand_Chat:
		return handler.Chat(ctx, body.Chat)
	case *pb.GameCommand_CommandBatch:
		return handler.CommandBatch(ctx, body.CommandBatch)
	default:
		return transportproblem.UnsupportedCommand("unsupported game command")
	}
}
